### ISSUE TITLE
How to use this script

### ISSUE THREAD

**Issue by linrakesh** [viveksyngh/ifsc-code#1]
Hi Vivek,
Could you guide me how to use this script as I am very new to Python. I am not able to use this script at all so that I could generate an excel sheet of all the banks details from RBI website.

Waiting to for your kind attention on this issue.

**Comment by viveksyngh** [comment]
I have pushed my changes and added readme on how to use files. Please have a look at it and let me know if your are still facing this issue.

**Comment by viveksyngh** [comment]
I have modified the readme and added steps to use this script.
